<a href="https://colab.research.google.com/github/zxrxuanrong/4050E024/blob/master/m20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/raspberry_pi/README.md

/bin/bash: https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/raspberry_pi/README.md: No such file or directory


In [ ]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 32.99 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [ ]:
!https://github.com/MyDearGreatTeacher/AI_and_security_2020

/bin/bash: https://github.com/MyDearGreatTeacher/AI_and_security_2020: No such file or directory


In [ ]:
!https://github.com/MyDearGreatTeacher/AI_and_security_2020/blob/master/20200921.md

/bin/bash: https://github.com/MyDearGreatTeacher/AI_and_security_2020/blob/master/20200921.md: No such file or directory


In [ ]:
import numpy as np

s = np.random.uniform(0,1,10) 
s

array([0.32800946, 0.82922164, 0.36563003, 0.35622077, 0.34659002,
       0.65228608, 0.5908512 , 0.27972726, 0.9996838 , 0.04499727])

In [18]:
np.ones(10)*10+1-2

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:

import numpy as np
 
arr1=np.ones((3,3))
arr2=np.array(arr1)
arr3=np.asarray(arr1)
arr1[1]=2
data1[1][1]=2
data1
arr3


SyntaxError: ignored

In [46]:
ar9=np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [50]:
import numpy as np
np.array([range(i,i+5)for i in[2,4,6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [53]:
np.tile(np.array([[1,2],[6,7]]),4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7, 6, 7]])

In [56]:
np.tile(np.array([[1,2],[6,7]]),[3,3])

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7],
       [1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7],
       [1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [57]:
x = np.arange(2,10).reshape(2,4)
x


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [58]:
y = np.arange(2,10).reshape(4,2)
y


array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
ar=np.array([np.arange(1,6),np.arange(10,15)]);
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])